### ISSUE TITLE
Do not use "latest" as image version

### ISSUE THREAD

**Issue by ironiemix** [linuxmuster/linuxmuster-mail#1]
It is bad practice to use the latest tag for productive docker environments, one should use a names version tag to have control over updates and the conseqences.

**Comment by ironiemix** [comment]
At the moment, "stable" points to "release-v6.1.0". This tag should IMHO be used. So when there is a new stable version upstream from tvial, we can first test the new stable version with linuxmuster.net before we change the tag for all users.

**Comment by HappyBasher** [comment]
Fixed in 0.3.0.
