### ISSUE TITLE
eMail-Alias: vorname.nachname@linuxmuster.domain.de

### ISSUE THREAD

**Issue by white-rabbit07** [linuxmuster/linuxmuster-mail#10]
Hallo.
Ist es möglich, anstelle von 
login@linuxmuster.meine-domain.de 
eine eMail-Adresse der Form
vorname.nachname@meine-domain.de 
zu erhalten?
Meine Vermutung: 
/srv/docker/linuxmuster-mail/config/postfix/ldap-aliases.cf
und evtl der Eintrag in der docker-compose.yml unter
DOVECOT_USER_FILTER?
Gibt es da nähere Infos?

Wie ist das, wenn Kollegen Doppelnamen haben? Erhalten die dann
Vorname.Nach-Name@ oder Vorname.NachName@?

Danke...

**Comment by HappyBasher** [comment]
This is no support medium. Use ask.linuxmuster.net for support, please.
