### ISSUE TITLE
v7: container startet nicht

### ISSUE THREAD

**Issue by white-rabbit07** [linuxmuster/linuxmuster-mail#7]
Hi. Ich habe vor einiger Zeit "linuxmuster-mail" auf unserem docker-host installiert.

Installierbar ist das Paket – aber es läuft nicht. Laut Doku soll es so sein:

 "Legt unterhalb von /srv/docker/linuxmuster-mail die Docker-Steuerdatei docker-compose.yml und diverse Bashskripte an."

Die bash-Scripte (start|stop|exec) sind da, aber von docker-compose.yml fehlt jede Spur … alles andere unter config ist ebenfalls leer.

 Commandline: apt install linuxmuster-mail
 Install: linuxmuster-mail:amd64 (0.4.1-0ubuntu0)

Any ideas?

**Comment by HappyBasher** [comment]
Das ist eigentlich als Helperskript für die Ersteinrichtung mit linuxmuster-setup auf dem Server gedacht. Will man das nachträglich machen, muss man die Datei /var/lib/linuxmuster/setup.ini vom Server auf die Dockermaschine kopieren. Dann kann man es als root mit
linuxmuster-mail.py -c setup.ini
einrichten.

**Comment by white-rabbit07** [comment]
Hallo.
Ok, das ist bisher nicht dokumentiert, nehme ich an? Ich habe das ausprobiert und es führte immer zu einem Abbruch des Scriptes: "Script finished with error!"
Nach etwas Debugging stellte sich folgendes heraus:
In deinem Python-Script wird die Variable binduserpw abgefragt und soll mit dem entsprechenden Eintrag aus der setup.ini ersetzt werden. Diese Variable kommt aber in der setup.ini gar nicht vor -- daher der Abbruch. Das ist also ein kleiner Bug.

Ich habe in der setup.ini nun sowohl bei der mailip als auch bei der dockerip die gleiche Adresse. Das dürfte aber kein Problem sein, denke ich?

Sollte dieser Container besser im grünen Netz laufen oder besser in der DMZ?

**Comment by HappyBasher** [comment]
Ergänzung:
In der setup.ini des Servers muss allerdings noch das Passwort des globalen Bindusers ergänzt werden. Das wird bei der Installation durch linuxmuster-setup erledigt und fehlt natürlich, wenn man das Mailsystem nachträglich einrichtet.
Das Passwort findet man auf dem Server in _/etc/linuxmuster/.secret/global-binduser_. Es muss so in die setup.ini eingetragen werden:
`binduserpw = geheim`

**Comment by HappyBasher** [comment]
Diskussion in welchem Kontext der Container laufen soll bitte in ask.linuxmuster.net führen.

**Comment by white-rabbit07** [comment]
Der docker-Container startet zwar nun (habe ihn jetzt in der DMZ) -- aber der Login als User scheitert leider weiterhin. Ich habe es unter Nextcloud --> Rainloop versucht.

In der Log-Datei auf dem docker-Host finde ich:
```
docker ps --> <ID> 
docker exec -it <ID> bash
cd /var/log/mail/
cat mail.warn
--->  Unable to bind to server ...   -1 (Can't contact LDAP server)
```

Der will sich über Port 389 und nicht 636 verbinden, obwohl in allen configs ausdrücklich Port 636 und ldap**s** angegegeben ist.
